<?php

namespace DoctorNet\Helper\Rights;

/**
 * @property boolean $canView
 * @property boolean $canRule
 * @property boolean $canDeal
 */
class EmployerMarketplaceRights extends AbstractHlBlockRights {
    
    /**
     * Set full right to Marketplace
     *
     * @return $this
     */
    public function setFullRights() {
        $this->canView = true;
        $this->canRule = true;
        $this->canDeal = true;
        
        return $this;
    }

    /**
     * Set null right to Marketplace
     *
     * @return $this
     */
    public function setNullRights() {
        $this->canView = false;
        $this->canRule = false;
        $this->canDeal = false;

        return $this;
    }

    public function setViewRights() {
        $this->canView = true;
    }
    
    protected function getHlBlockId() {
        return 5;
    }
    
    protected function getUserIdFieldName() {
        return 'UF_USER_ID';
    }
    
    protected function getLinkedIdFieldName() {
        return 'UF_MARKETPLACE_ID';
    }

    public function save() {
        return parent::save(); // TODO: Change the autogenerated stub
    }
}